config_name: "Dyode Receiver"
config_version: 1.0
config_date: 19-06-2023

max_bitrate: 100 # maximum bitrate

dyode_sender:
  ip: 172.10.0.1
  # mac: 20:7b:d2:7d:f2:a3

dyode_receiver:
  interface: ens33
    

modules:
  filereceiver:
    type: filereceiver
    port: 9700
    bitrate: 20 # in Mb/s
    timeout: 30  # in second
    fec: "4x4"   # forward error correction
    in: /home/highside/dyode
    out: /home/lowside/dyode
    temp: /home/lowside/temp
  # modbus:
  #   type: modbus
  #   port: 9500
  #   ip: 127.0.0.1
  #   port_out: 503
  #   registers:
  #     - 0-10
  #     - 400-402
  #   coils:
  #     - 0-10
  #     - 100-110
  screen:
    type: screen
    port: 9900
    in: /home/highside/screen
    out: /home/lowside/screen
